name: Build and Zip Artifacts on Tag Push

on:
    push:
        tags:
            - "*"

jobs:
    build-and-archive:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "14"

            - name: Install Dependencies
              run: npm install

            - name: Build Project
              run: npm run build

            - name: Zip dist folder
              run: zip -r dist-${{ github.ref_name }}.zip dist

            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: dist-${{ github.ref_name }}.zip
                  path: dist-${{ github.ref_name }}.zip
