name: Build and Zip Artifacts on Tag Push

on:
    push:
        tags:
            - "*"

jobs:
    build-and-archive:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: ".nvmrc"
                  cache: "npm"

            - name: Install Dependencies
              run: npm ci

            - name: Build Project
              run: npm run build

            - name: Zip dist folder
              run: zip -r dist-${{ github.ref_name }}.zip dist

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dist-${{ github.ref_name }}
                  path: dist-${{ github.ref_name }}.zip
